apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: apidemo-deployment
spec:
  selector:
    matchLabels:
      app: apidemo
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: apidemo
    spec:
      containers:
      - name: apidemo
        image: 211752457047.dkr.ecr.us-west-2.amazonaws.com/apidemo:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 9000
